name: OpenAPI Diff
on:
  pull_request:
    branches:
      - "**"
jobs:
  diff:  
    name: Realize diff between two files
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          echo ${{ github.repository }}
          echo ${{ github.ref_name }}

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v40
        with:
            files: |
                *.yml
                *.yaml
  
      - name: List all added files
        run: |
            for file in ${{ steps.changed-files.outputs.added_files }}; do
                echo "$file was added"
            done
      - name: Running OpenAPI Spec diff action
        uses: oasdiff/oasdiff-action/diff@main
        with:
            base: 'swagger-apis/payments/4.0.0-beta.6.yml'
            revision: 'swagger-apis/payments/4.0.0-beta.7.yml'
            format: text